/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDecisionCenterRouteImport } from './routes/ai-decision-center'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SimulationCenterRouteImport } from './routes/simulation-center'
import { Route as WarehousesRouteImport } from './routes/warehouses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDecisionCenterRoute = AiDecisionCenterRouteImport.update({
  id: '/ai-decision-center',
  path: '/ai-decision-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationCenterRoute = SimulationCenterRouteImport.update({
  id: '/simulation-center',
  path: '/simulation-center',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/analytics': typeof AnalyticsRoute
  '/fleet': typeof FleetRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulation-center': typeof SimulationCenterRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/analytics': typeof AnalyticsRoute
  '/fleet': typeof FleetRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulation-center': typeof SimulationCenterRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-decision-center': typeof AiDecisionCenterRoute
  '/analytics': typeof AnalyticsRoute
  '/fleet': typeof FleetRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/simulation-center': typeof SimulationCenterRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-decision-center'
    | '/analytics'
    | '/fleet'
    | '/settings'
    | '/shipments'
    | '/simulation-center'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-decision-center'
    | '/analytics'
    | '/fleet'
    | '/settings'
    | '/shipments'
    | '/simulation-center'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/ai-decision-center'
    | '/analytics'
    | '/fleet'
    | '/settings'
    | '/shipments'
    | '/simulation-center'
    | '/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDecisionCenterRoute: typeof AiDecisionCenterRoute
  AnalyticsRoute: typeof AnalyticsRoute
  FleetRoute: typeof FleetRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SimulationCenterRoute: typeof SimulationCenterRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-decision-center': {
      id: '/ai-decision-center'
      path: '/ai-decision-center'
      fullPath: '/ai-decision-center'
      preLoaderRoute: typeof AiDecisionCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation-center': {
      id: '/simulation-center'
      path: '/simulation-center'
      fullPath: '/simulation-center'
      preLoaderRoute: typeof SimulationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDecisionCenterRoute: AiDecisionCenterRoute,
  AnalyticsRoute: AnalyticsRoute,
  FleetRoute: FleetRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SimulationCenterRoute: SimulationCenterRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
